---
title: "Sismos en Chile"
author: "Sara Vidal"
date: "2025-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Revisando una base de Datos Sísmicos de Chile

### Cargamos librerías
library(dplyr)
library(readr)
library(lubridate)
library(dplyr)
library(ggplot2)

### Cargamos la base de datos
datos <- read.csv("~/Desktop/Datos/Individual 2/Datos sismicos/seismic_data.csv")

## Limpiamos la base de datos
### Renombramos las columnas en español
colnames(datos) <- c("Fecha", "Latitud", "Longitud", "Profundidad_km", "Magnitud")

### Convertimos la columna Fecha a formato fecha-hora y eliminaremos las fechas inválidas. Para eso utilizaremos mutate y filter.
datos <- datos %>%
  mutate(Fecha = ymd_hms(Fecha)) %>%
  filter(!is.na(Fecha))
  
  
### Ordenamos por fecha con arrange
datos <- datos %>% arrange(Fecha)

### Eliminamos los duplicados con distinct
datos <- datos %>% distinct()

### Verificamos la estructura con str
str(datos)


## Realizamos un análisis descriptivo

### Realizamos un resumen rápido con summary
summary(datos)

### Revisamos el rango de fechas y magnitudes usando cat que permite imprimir con presentación el mínimo y máximo.
cat("Rango de fechas:", min(datos$Fecha), "a", max(datos$Fecha), "\n")
cat("Rango de magnitudes:", min(datos$Magnitud), "a", max(datos$Magnitud), "\n")

#### El Rango de fechas sería 2012-03-03 11:01:47 a 2025-05-26 03:50:27 y el Rango de magnitudes es de 2.3 a 8.4 grados.

### ¿Cuántos sismos ocurrieron por año?
#### Para eso vamos a extraer el año de la columna `Fecha` con mutate en una nueva base, después agrupamos por año con gruoup_by y contamos los eventos con summarise, ordenamos de mayor a menor con arrange y luego mostramos el primer registro (el año con más eventos) creando una variable (año_max).
sismos_por_año <- datos %>%
  mutate(Año = year(Fecha)) %>%
  group_by(Año) %>%
  summarise(Eventos = n()) %>%
  arrange(desc(Eventos))
  
año_max <- sismos_por_año %>% slice(1)
cat("El año con más eventos sísmicos fue:", año_max$Año, "con", año_max$Eventos, "eventos.")

####El año con más eventos sísmicos fue 2019 con 479 eventos.


### ¿En qué fechas fueron los sismos con mayor magnitud?
#### Filtramos los sismos con magnitud mayor a 6 (eventos extremos) creando una nueva columna sismos_extremos, luego filtramos y ordenamos de mayor a menor con arrange. Luego mostramos las fechas y magnitudes.

sismos_extremos <- datos %>%
  filter(Magnitud > 6) %>%
  arrange(desc(Magnitud))

sismos_extremos %>%
  select(Fecha, Magnitud) %>%

### Calculamos el promedio de magnitud y profundidad de los sismos con mayor magnitud. Utilizamos summarise y mean para calcular el promedio.
promedios <- sismos_extremos %>%
  summarise(
    Promedio_Magnitud = mean(Magnitud, na.rm = TRUE),
    Promedio_Profundidad = mean(Profundidad_km, na.rm = TRUE),
    Total_Eventos = n()
  )
  
##Visualización de datos
### Línea temporal de sismos de alta magnitud. 
#### Para esto utilizamos ggplot, filtrando los sismos con magnitud mayor a 6, ordenando por fecha para la línea temporal y usando `geom_line()` para la tendencia y `geom_point()` para destacar cada evento.

ggplot(sismos_extremos, aes(x = Fecha, y = Magnitud)) +
  geom_line(color = "#E69F00", size = 1) +
  geom_point(color = "#E69F00", size = 3) +
  labs(title = "Eventos Sísmicos con Magnitud > 6",
       x = "Fecha",
       y = "Magnitud") +
  theme_minimal()

### ¿Cuántos sismos hubo por año?
#### Para esto utilizamos ggplot, filtrando los sismos_por_año.

ggplot(sismos_por_año, aes(x = Año, y = Eventos)) +
  geom_bar(stat = "identity", fill = "#C4B4FF") +
  geom_text(aes(label = Eventos), vjust = -0.5) +
  labs(title = "Cantidad de Sismos por Año",
       x = "Año",
       y = "Número de Sismos") +
  theme_minimal()
  
### Los 10 sismos más fuertes ordenado por magnitud
####En este caso `arrange(desc(Magnitud))`: ordena los sismos por magnitud de mayor a menor, luego `slice(1:10)`: toma los 10 primeros, `coord_flip()`: invierte los ejes para que las fechas se lean mejor y finalmente `reorder(Fecha, Magnitud)`: ordena las barras según magnitud.

top10_sismos <- datos %>%
  arrange(desc(Magnitud)) %>%
  slice(1:10) %>%
  select(Fecha, Magnitud)

ggplot(top10_sismos, aes(x = reorder(Fecha, Magnitud), y = Magnitud)) +
  geom_bar(stat = "identity", fill = "#C4B4FF") +
  coord_flip() +  # Para que las fechas queden en el eje Y
  labs(title = "Top 10 Sismos Más Fuertes",
       x = "Fecha",
       y = "Magnitud") +
  theme_minimal()


### Terminamos este análisis guardando las nuevas bases de datos y los gráficos
write_csv(sismos_por_año, "~/Desktop/Datos/Individual 2/Datos sismicos/sismos_por_año.csv")
write_csv(sismos_extremos, "~/Desktop/Datos/Individual 2/Datos sismicos/sismos_extremos.csv")
write_csv(promedios, "~/Desktop/Datos/Individual 2/Datos sismicos/promedios.csv")
write_csv(año_max, "~/Desktop/Datos/Individual 2/Datos sismicos/año_max.csv")
write_csv(top10_sismos, "~/Desktop/Datos/Individual 2/Datos sismicos/top10_sismos.csv")


### El siguiente trabajo tuvo como objetivo analizar datos de sismología de Chile extraídos de la base de datos de Kaggle: https://www.kaggle.com/datasets/nicolasgonzalezmunoz/earthquakes-on-chile
